#!/bin/sh

#Caminho do ficheiro: /var/ossec/integrations/custom-wazuh-email

WPYTHON_BIN="framework/python/bin/python3"

SCRIPT_PATH="$0.py"

DIR_NAME="$(cd "$(dirname "$0")"; pwd -P)"

case ${DIR_NAME} in
    */active-response/bin | */wodles*)
        if [ -z "${WAZUH_PATH}"]; then
            WAZUH_PATH="$(cd "${DIR_NAME}/../.."; pwd)"
        fi

        PYTHON_SCRIPT="${DIR_NAME}/${SCRIPT_PATH##*/}"
        ;;
    */bin)
        if [ -z "${WAZUH_PATH}" ]; then
            WAZUH_PATH="$(cd "${DIR_NAME}/.."; pwd)"
        fi

        PYTHON_SCRIPT="${WAZUH_PATH}/framework/scripts/${SCRIPT_PATH##*/}"
        ;;
    *)
        if [ -z "${WAZUH_PATH}" ]; then
            WAZUH_PATH=$(cd "${DIR_NAME}/.."; pwd)
        fi

        PYTHON_SCRIPT="${DIR_NAME}/${SCRIPT_PATH##*/}"
        ;;
esac

${WAZUH_PATH}/${WPYTHON_BIN} "${PYTHON_SCRIPT}" "$@"