''' 
##########################
Neste ficheiro constam apenas as alterações realizadas neste
mesmo ficheiro na máquina virtual, já que este é um ficheiro
já existente previamente.
########################
''' 

''' 
##################
ALTERADO
##################
'''

''' 
Caminho do ficheiro: /var/ossec/etc/ossec.conf
'''

<global>
  <email_notification>yes</email_notification>
  <smtp_server>127.0.0.1</smtp_server>
  <email_from>luismiguelpaiva70@gmail.com</email_from>
  <email_to>luismiguelpaiva70@gmail.com</email_to>
  <email_maxperhour>100</email_maxperhour>
  <email_log_source>alerts.log</email_log_source>
</global>

<alerts>
  <log_alert_level>3</log_alert_level>
  <email_alert_level>8</email_alert_level>
</alerts>

''' 
##################
ADICIONADO
##################
'''

<integration>
  <name>custom-wazuh-email</name>
  <level>8</level>
  <alert_format>json</alert_format>
</integration>